name: Github actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest


  strategy:
    matrix:
      python-version: [3.8, 3.9]

  steps:
    - name: checkout the code
      uses: actions/checkout@v3
    - name: set python
      uses: actions/python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependancies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run the test
      run: |
        cd src
        python -m pytest addition.py                
